[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "HomeRangeToolbox"
authors = [{name = "Levente Juhasz", email = "ljuhasz@fiu.edu"}]
dynamic = ["version", "description"]
